# Generated by Django 5.2.6 on 2025-12-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0002_user_alter_comment_user_alter_like_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unsername',
            new_name='username',
        ),
    ]
