# Generated by Django 5.2.6 on 2025-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0003_rename_unsername_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
