# Generated by Django 5.2.6 on 2025-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0004_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_path',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='', upload_to='posts/'),
        ),
    ]
