# Generated by Django 5.2.6 on 2025-12-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0005_remove_post_file_path_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rada_app.user'),
        ),
    ]
