# Generated by Django 5.2.6 on 2025-12-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0007_alter_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
