# Generated by Django 5.2.6 on 2025-12-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0008_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
