# Generated by Django 5.2.6 on 2025-12-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0009_remove_comment_user_remove_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
