# Generated by Django 5.2.6 on 2025-12-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0013_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='auteur',
        ),
    ]
