# Generated by Django 5.2.6 on 2026-01-08 19:18

import rada_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rada_app', '0015_remove_like_liked_at_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/', validators=[rada_app.models.validate_image]),
        ),
    ]
